name: Deployer sur shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Setup R dependencies (rsconnect + app)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rsconnect
            any::shiny
            any::readxl
            any::tidyr
            any::dplyr
            any::plotly
            any::shinyWidgets
            any::bslib
            any::lubridate
            any::cpp11

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -e "options(repos = c(CRAN = 'https://cran.rstudio.com/'));
               rsconnect::setAccountInfo(
                 name   = Sys.getenv('SHINYAPPS_NAME'),
                 token  = Sys.getenv('SHINYAPPS_TOKEN'),
                 secret = Sys.getenv('SHINYAPPS_SECRET')
               );
               rsconnect::deployApp(
                 '.',
                 appName       = 'RH-Pay-Insights',
                 logLevel      = 'normal',
                 forceUpdate   = TRUE,
                 envManagement = 'none'
               )"
